### ISSUE TITLE
The download of datasets

### ISSUE THREAD

**Issue by CSU-KangHu** [manisa/ClassifyTE#4]
Hello, I want to download the PGSB and REPBASE datasets, but I cannot find the link in your paper or GitHub. I navigated to the referenced paper "Top-down strategies for hierarchical classification of transposable elements with neural networks" and found a broken link at https://www.dropbox.eom/s/15dsuyj78h1fid4/TE_IJCNN2.zip?dl=0. Can you please let me know where I can download these two datasets?

**Comment by manisa** [comment]
Hi, You can find datasets used in this study here: https://github.com/manisa/ClassifyTE#download-datasets
